#!/usr/bin/env python3
"""
push.py — YAML intermediate file → Clockify time entries
=========================================================
Reads the YAML file produced by generate.py and creates the corresponding
time entries in Clockify.

Duplicate detection uses the local SQLite database (clockify_sync.db) so no
extra Clockify API calls are needed. The database is updated after each
successful push.

Usage:
    python push.py
    python push.py --file clockify_2026-04.yaml
    python push.py --dry-run
    python push.py --date 2026-04-07
    python push.py --file clockify_2026-04.yaml --dry-run --verbose
    python push.py --force          # ignore last sync date
"""

from __future__ import annotations

import argparse
import logging
import sys
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Optional
from zoneinfo import ZoneInfo

try:
    import requests
    import yaml
except ImportError as exc:
    sys.exit(f"ERROR: Missing dependency — {exc}. Run: pip install -r requirements.txt")

import db


# ─── Logging ─────────────────────────────────────────────────────────────────

def setup_logging(verbose: bool) -> None:
    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.INFO,
        format="%(asctime)s [%(levelname)-8s] %(message)s",
        datefmt="%H:%M:%S",
    )


log = logging.getLogger(__name__)


# ─── Data structures ─────────────────────────────────────────────────────────

@dataclass
class EntryRecord:
    """A single parsed entry from the YAML file."""
    date: date
    project_name: str
    hours: Optional[float]
    description: str


@dataclass
class RunSummary:
    created: int = 0
    skipped_duplicate: int = 0
    skipped_null_hours: int = 0
    skipped_already_synced: int = 0
    errors: int = 0
    last_created_date: Optional[date] = None
    null_entries: list[str] = field(default_factory=list)


# ─── Config & YAML loading ───────────────────────────────────────────────────

def load_config(path: Path) -> dict:
    """Load and minimally validate config.yaml."""
    if not path.exists():
        sys.exit(f"ERROR: Config file not found: {path}")
    with path.open(encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    required = ("clockify_api_key", "clockify_workspace_id", "clockify_user_id")
    for key in required:
        if not cfg.get(key):
            sys.exit(f"ERROR: Missing required config field: '{key}'")

    cfg.setdefault("timezone", "UTC")
    cfg.setdefault("workday_start", "09:00")
    return cfg


def load_yaml_file(path: Path) -> dict:
    """Load the intermediate YAML produced by generate.py."""
    if not path.exists():
        sys.exit(f"ERROR: YAML file not found: {path}")
    with path.open(encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict) or "entries" not in data:
        sys.exit(f"ERROR: Unexpected YAML structure in {path}. Was it generated by generate.py?")
    return data


def parse_entries(yaml_data: dict) -> list[EntryRecord]:
    """Flatten the YAML structure into a list of EntryRecord objects."""
    records: list[EntryRecord] = []
    for day_block in yaml_data.get("entries", []):
        try:
            entry_date = date.fromisoformat(str(day_block["date"]))
        except (KeyError, ValueError) as exc:
            log.warning(f"Skipping malformed date block: {exc}")
            continue
        for entry in day_block.get("entries", []):
            records.append(EntryRecord(
                date=entry_date,
                project_name=str(entry.get("project", "")),
                hours=entry.get("hours"),
                description=str(entry.get("description", "")),
            ))
    return records


# ─── Clockify API client ─────────────────────────────────────────────────────

CLOCKIFY_BASE = "https://api.clockify.me/api/v1"


class ClockifyClient:
    """Thin wrapper around the Clockify REST API v1."""

    def __init__(self, api_key: str, workspace_id: str, user_id: str) -> None:
        self.workspace_id = workspace_id
        self.user_id      = user_id
        self._session     = requests.Session()
        self._session.headers.update({
            "X-Api-Key":    api_key,
            "Content-Type": "application/json",
        })
        self._project_cache: Optional[dict[str, str]] = None

    def _get(self, path: str, params: Optional[dict] = None) -> object:
        resp = self._session.get(f"{CLOCKIFY_BASE}{path}", params=params, timeout=30)
        self._check(resp)
        return resp.json()

    def _post(self, path: str, body: dict) -> dict:
        resp = self._session.post(f"{CLOCKIFY_BASE}{path}", json=body, timeout=30)
        self._check(resp)
        return resp.json()

    @staticmethod
    def _check(resp: requests.Response) -> None:
        if resp.ok:
            return
        code = resp.status_code
        messages = {
            400: f"Bad request (400). Payload: {resp.text[:300]}",
            401: "Invalid or expired Clockify API key (401).",
            403: "Access denied (403). Check workspace_id and permissions.",
            404: f"Not found (404): {resp.url}",
            429: "Rate limit exceeded (429). Wait a moment and retry.",
        }
        sys.exit(f"ERROR: Clockify API — {messages.get(code, f'HTTP {code}: {resp.text[:300]}')}")

    def get_project_map(self) -> dict[str, str]:
        """
        Return {project_name: project_id} cached from a single API call.
        Endpoint: GET /workspaces/{wid}/projects?page-size=500
        """
        if self._project_cache is not None:
            return self._project_cache
        log.info("Fetching Clockify projects …")
        projects = self._get(
            f"/workspaces/{self.workspace_id}/projects",
            params={"page-size": 500},
        )
        if not isinstance(projects, list):
            sys.exit("ERROR: Unexpected response fetching Clockify projects.")
        self._project_cache = {p["name"]: p["id"] for p in projects}
        return self._project_cache

    def resolve_project_id(self, name: str) -> str:
        mapping = self.get_project_map()
        pid = mapping.get(name)
        if not pid:
            available = ", ".join(f"'{n}'" for n in sorted(mapping))
            sys.exit(
                f"ERROR: Project '{name}' not found in Clockify.\n"
                f"Available projects: {available}"
            )
        return pid

    def create_time_entry(self, payload: dict) -> dict:
        """
        Create a new time entry.
        Endpoint: POST /workspaces/{wid}/time-entries
        """
        return self._post(
            f"/workspaces/{self.workspace_id}/time-entries",
            body=payload,
        )


# ─── Time helpers ─────────────────────────────────────────────────────────────

def make_utc_times(
    entry_date: date,
    hours: float,
    timezone: str,
    workday_start: str = "09:00",
    start_override: Optional[datetime] = None,
) -> tuple[str, str]:
    """
    Return (start_utc, end_utc) ISO-8601 strings for an entry.
    First entry of the day starts at workday_start local time.
    Subsequent entries on the same day use start_override to avoid overlaps.
    """
    if start_override is not None:
        utc_start = start_override
    else:
        tz = ZoneInfo(timezone)
        h, m = (int(x) for x in workday_start.split(":"))
        local_start = datetime(entry_date.year, entry_date.month, entry_date.day,
                               h, m, 0, tzinfo=tz)
        utc_start = local_start.astimezone(ZoneInfo("UTC"))

    utc_end = utc_start + timedelta(hours=hours)
    return (
        utc_start.strftime("%Y-%m-%dT%H:%M:%SZ"),
        utc_end.strftime("%Y-%m-%dT%H:%M:%SZ"),
    )


# ─── Entry processing ─────────────────────────────────────────────────────────

def process_entries(
    records: list[EntryRecord],
    client: ClockifyClient,
    timezone: str,
    workday_start: str,
    dry_run: bool,
    filter_date: Optional[date],
    last_sync_date: Optional[date],
) -> RunSummary:
    """
    Iterate over records and create Clockify entries (or simulate in dry-run).

    Duplicate detection uses the local SQLite push_log — no extra API calls.
    Successfully created entries are logged to SQLite immediately.
    """
    summary = RunSummary()

    # --date filter
    if filter_date:
        records = [r for r in records if r.date == filter_date]
        if not records:
            log.warning(f"No entries found for date {filter_date} in the YAML file.")
            return summary

    # Skip dates already covered by last sync
    if last_sync_date and not filter_date:
        before  = [r for r in records if r.date <= last_sync_date]
        records = [r for r in records if r.date > last_sync_date]
        if before:
            summary.skipped_already_synced = len(before)
            log.info(
                f"Skipping {len(before)} record(s) on or before {last_sync_date}. "
                "Use --force to override."
            )

    # Tracks end time per date so consecutive entries don't overlap
    last_end_by_date: dict[date, datetime] = {}

    for record in records:
        label = f"{record.date}  [{record.project_name}]"

        # Null hours
        if record.hours is None:
            log.warning(f"  SKIP (hours=null): {label}")
            summary.skipped_null_hours += 1
            summary.null_entries.append(f"{record.date}  {record.project_name}")
            continue

        # Local duplicate check (SQLite — no API call needed)
        if not dry_run and db.was_pushed(record.date, record.project_name, record.description):
            log.info(f"  SKIP (duplicate):  {label}")
            summary.skipped_duplicate += 1
            continue

        project_id = client.resolve_project_id(record.project_name)

        start_utc, end_utc = make_utc_times(
            record.date, record.hours, timezone,
            workday_start=workday_start,
            start_override=last_end_by_date.get(record.date),
        )

        # Advance cursor so the next entry on this date starts here
        last_end_by_date[record.date] = datetime.strptime(
            end_utc, "%Y-%m-%dT%H:%M:%SZ"
        ).replace(tzinfo=ZoneInfo("UTC"))

        payload = {
            "start":       start_utc,
            "end":         end_utc,
            "description": record.description,
            "projectId":   project_id,
        }

        if dry_run:
            log.info(
                f"  [DRY RUN]  {label}  "
                f"{record.hours}h  {start_utc} → {end_utc}\n"
                f"             {record.description[:80]}"
            )
            summary.created += 1
        else:
            try:
                result = client.create_time_entry(payload)
                clockify_id = result.get("id")
                log.info(f"  CREATED    {label}  {record.hours}h  {start_utc} → {end_utc}")
                db.log_push(
                    record.date, record.project_name,
                    record.description, record.hours, clockify_id,
                )
                summary.created += 1
                summary.last_created_date = record.date
            except SystemExit as exc:
                log.error(f"  ERROR creating {label}: {exc}")
                summary.errors += 1

    return summary


# ─── CLI & main ──────────────────────────────────────────────────────────────

def default_yaml_path() -> Path:
    return Path(f"clockify_{date.today().strftime('%Y-%m')}.yaml")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="push",
        description="Push YAML time entries to Clockify.",
    )
    parser.add_argument("--file", metavar="FILE", type=Path, default=None)
    parser.add_argument("--config", metavar="FILE", type=Path, default=Path("config.yaml"))
    parser.add_argument("--dry-run", action="store_true",
                        help="Simulate without creating entries")
    parser.add_argument("--date", metavar="YYYY-MM-DD", default=None,
                        help="Process only this date")
    parser.add_argument("--force", action="store_true",
                        help="Ignore last sync date, re-process all entries")
    parser.add_argument("--verbose", "-v", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    setup_logging(args.verbose)

    yaml_path = args.file or default_yaml_path()

    filter_date: Optional[date] = None
    if args.date:
        try:
            filter_date = date.fromisoformat(args.date)
        except ValueError:
            sys.exit(f"ERROR: --date must be YYYY-MM-DD, got '{args.date}'.")

    log.info(f"=== push.py | file={yaml_path} | dry_run={args.dry_run} ===")

    # ── Init DB (migrate from old .sync_state.json if present) ──────────────
    db.init_db()
    db.migrate_from_json(Path(".sync_state.json"))

    # ── Load inputs ──────────────────────────────────────────────────────────
    cfg           = load_config(args.config)
    yaml_data     = load_yaml_file(yaml_path)
    records       = parse_entries(yaml_data)
    timezone      = cfg["timezone"]
    workday_start = cfg["workday_start"]

    log.info(f"Loaded {len(records)} record(s) from {yaml_path} (month: {yaml_data.get('month', '?')})")

    if not records:
        log.warning("No entries to process.")
        return

    # ── Sync state ───────────────────────────────────────────────────────────
    last_sync_date: Optional[date] = None
    if not args.force:
        last_sync_date = db.get_last_sync_date()
        if last_sync_date:
            log.info(f"Last sync date: {last_sync_date}  (--force to override)")

    # ── Clockify client ──────────────────────────────────────────────────────
    client = ClockifyClient(
        api_key=cfg["clockify_api_key"],
        workspace_id=cfg["clockify_workspace_id"],
        user_id=cfg["clockify_user_id"],
    )

    # ── Process ──────────────────────────────────────────────────────────────
    summary = process_entries(
        records=records,
        client=client,
        timezone=timezone,
        workday_start=workday_start,
        dry_run=args.dry_run,
        filter_date=filter_date,
        last_sync_date=last_sync_date,
    )

    # ── Persist sync state ───────────────────────────────────────────────────
    if not args.dry_run and summary.last_created_date:
        db.set_last_sync_date(summary.last_created_date)
        log.info(f"Sync state updated → {summary.last_created_date}")

    # ── Summary ──────────────────────────────────────────────────────────────
    verb = "simuladas" if args.dry_run else "creadas"
    print()
    print("=" * 54)
    print(f"  RESUMEN{' [DRY RUN]' if args.dry_run else ''}")
    print("=" * 54)
    print(f"  Entradas {verb:<13}: {summary.created}")
    print(f"  Saltadas (ya sync.) : {summary.skipped_already_synced}")
    print(f"  Saltadas (duplicado): {summary.skipped_duplicate}")
    print(f"  Saltadas (null hrs) : {summary.skipped_null_hours}")
    if summary.errors:
        print(f"  Errores             : {summary.errors}")

    if summary.null_entries:
        print()
        print("  Pendientes de revisión manual (hours=null):")
        for label in summary.null_entries:
            print(f"    - {label}")
        print()
        print("  Edita el YAML, rellena las horas y vuelve a ejecutar push.py.")

    print("=" * 54)


if __name__ == "__main__":
    main()
